### ISSUE TITLE
Error login Ziggo Go

### ISSUE THREAD

**Issue by TheNoxx** [dut-iptv/dut-iptv#126]
**Describe the bug**
error login Ziggo Go ; absolute sure password is correct

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/7497699/170445055-b8d7726e-c668-4e11-bde2-7c340119980c.png)

**Device (please complete the following information):**
- Type: Nvidia Shield 2021
 - OS: Android TV
 - Kodi Version 19.4
 - Addon Version : Latest

**Additional context**
I use kodi build XENON 
![Uploading image.png…]()

Kind regards

**Comment by TheNoxx** [comment]
Better pictures with error 
![image](https://user-images.githubusercontent.com/7497699/170453699-aa02cae5-4cb5-423f-97f1-10e9b4100b31.png)
![image](https://user-images.githubusercontent.com/7497699/170453765-27a93da4-17b0-4b21-a6e0-bb464d8e3d1b.png)

**Comment by pipo1000** [comment]
I have the same problem for a couple of weeks.

**Comment by nhlau87** [comment]
I have exact the same issue with the same KeyError on my Fire TV.

**Comment by suntory1980** [comment]
I have also exact the same issue using fresh Kodi matrix install with firestick tv

**Comment by tketke** [comment]
Also same problem, not able to log in after fresh instal., Atemtped Fresh installdue to only clear nedl1,2,3.

**Comment by ScapSie** [comment]
Same problem here. Fresh install.

**Comment by hansheijmans** [comment]
Same here, Kodi on Raspberry Pi 4, Fresh install.

App remembers login credentials though. Went though the install procedure, also installed missing python3 elements.

**Comment by brunoj** [comment]
Same here, Kodi on Raspberry 3B+, also fresh install.

**Comment by Smollejan** [comment]
Same here

**Comment by 3DSBricker** [comment]
For anyone having this problem or can't stream anything else than live TV NPO 1/2/3, see #135 and my pull request #136. In the issue I have explained how to install it, I will make it easier to install once I fixed the major problems. You can already stream all live TV channels and replay everything up to 7 days (haven't tested with subscriptions only allowing up to 2 days).

**Comment by hansheijmans** [comment]
Downloaded the repository again. Installed the add-on but still same error as user @TheNoxx subscribes.

Edit: after restarting the add-on apparently the login succeeded but any attempt to start a (live) stream failed with same error.

I thought is was fixed? Or should I do something more?

**Comment by 3DSBricker** [comment]
No it isn't fixed. I linked my pull request and issue for the information. This repository is dead for now, mine does work. There still are some minor issues, though, but I'm working on fixing them.

**Comment by Eddict** [comment]
can it be related to the two-step authentication Ziggo (Vodafone) introduced?
it is a forced extra step now here; https://www.vodafone.nl/account/inloggen?login=ziggo-selfcare

**Comment by mstreurman** [comment]
Same issue here. Trying to log in to Ziggo Go using this plugin gives me the error message "Error Logging in to Ziggo. Check your username and password" which I of course did, they work on their website www.ziggogo.tv and in the Ziggo Go App. So I tried a couple of times more just to make sure I didn't make any typing errors, but sadly enough we it doesn't log in at all.

Kodi 19.4 Matrix in Windows 11 22h2 with all the latest patches, from Croatia.

**Comment by 3DSBricker** [comment]
As I said before, I fixed replay and live TV. Except replay sort-of stopped working. The whole EPG is down and I can't do anything about it. I will try to get recordings working instead. And no, it is not related to any 2FA, you most likely did not make any typo, restarting after a failed login does **not** make it logged in, that is a bug. 

So for now, live TV works without EPG, replay does not work anymore for the end user, neither does search as it uses the EPG. But you **do** need to download **my** repository using the link included in my first post in this issue.
